#!/bin/bash

set -euo pipefail

apt update
apt upgrade --yes

# https://unix.stackexchange.com/questions/90227/why-is-there-no-https-transport-for-debian-apt-tool
apt install --yes "apt-transport-https" "ca-certificates"

for file in $(find -L "$HOME/.config/dotfile" -maxdepth 1 -name "Aptfile.*" -type f); do
  source "$file"
done

apt autoremove --yes
