#!/bin/bash

set -euo pipefail

apt update

# https://docs.brew.sh/Homebrew-on-Linux#debian-or-ubuntu
apt upgrade --yes "build-essential" "procps" "curl" "wget" "file" "git" "python"

# https://unix.stackexchange.com/questions/90227/why-is-there-no-https-transport-for-debian-apt-tool
apt upgrade --yes "apt-transport-https"

# https://stackoverflow.com/questions/53343801/how-do-i-get-the-man-command
apt upgrade --yes "man-db"

apt autoremove --yes
