tap "homebrew/bundle"
tap "homebrew/core"

brew "asdf"
brew "bash"
brew "bat"
brew "curl"
brew "exa"
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "git-delta"
brew "gnupg"
brew "gron"
brew "jq"
brew "just"
brew "neovim"
brew "rargs"
brew "rcm"
brew "ripgrep"
brew "sd"
brew "selene"
brew "shellcheck"
brew "shfmt"
brew "starship"
brew "stylua"
brew "tmux"
brew "watchexec"
brew "yq"

Dir.glob(File.join(File.expand_path("~/.config/dotfile"), "Brewfile.*")) do |path|
  instance_eval(File.read(path))
end
