# source prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source ~/.common_zshrc
source ~/.common_shrc

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
