source ~/.commonenv

# Changes to path reflected in dmenu_run
export PATH=$PATH:/opt/java/bin

# Improve Java font rendering
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
