source ~/.commonshrc

plugins=(archlinux catimg colored-man command-not-found extract git git-extras nvm rbenv redis-cli ssh-agent systemd vi-mode zsh-syntax-highlighting history-substring-search)
source ~/.common_zshrc

# set up virtualenv for python (with wrapper for commands)
export WORKON_HOME=~/.virtualenvs
export VIRTUAL_ENV_DISABLE_PROMPT=1
source /usr/bin/virtualenvwrapper.sh
workon global
