#!/usr/bin/env bash
set -euo pipefail

function main() {
  local args=()

  while [ $# -gt 0 ]; do
    case $1 in
    get)
      "${args[@]}"
      break
      ;;

    store)
      break
      ;;

    forget)
      break
      ;;

    *)
      args+=("$1")
      shift
      ;;
    esac
  done
}

main "$@"
